### ISSUE TITLE
How to enable DC/DAL in the Kernel

### ISSUE THREAD

**Issue by Bulbyzarr** [automorphism88/amd-staging-sources#1]
Hi, 

I'm interested to build the latest amd-staging kernel 4.11 on Gentoo and i need your help.
Which are the options to enable to have HDMI and others features working for my Rx560 ?

Thanks,
Maxime

**Comment by automorphism88** [comment]
Hi,

There is an option in the kernel configuration to enable the DC code, if you're using the staging tree from git. Just go to the section where you enable the AMDGPU driver and it's one of the options there. If the option is enabled in the configuration it will be enabled at boot by default. You'll also need to enable the appropriate settings in the sound section.

Also this repo is just for the 4.9 LTS kernels, but I have ebuilds for the 4.11 and 4.12 kernels in my Gentoo overlay at https://github.com/automorphism88/gentoo-overlay (also an xml file so you can add it to layman if you want). However, be warned that the amdstaging-sources ebuilds use git to automatically merge the minor patches from kernel.org into the git tree from AMD and it's possible that the result might sometimes fail to compile. I don't reboot very often and haven't tested all the versions. In case of problems I also include a 4.x.0 ebuild when I version bump for testing purposes.

There's also an ebuild in my overlay called mbab-sources, which uses the kernel tree from https://github.com/M-Bab/linux-kernel-amdgpu, plus the Gentoo patchset. The maintainer of that repo manually merges updates so it should at least compile. I haven't updated it in awhile since I don't use it anymore but you could version bump it yourself in a local overlay and it should work.
